---
title: '我把青春献给你：排版 (3)'
author: 赵鹏
date: '2017-12-23'
slug: latex-and-me-3
summary: "LaTeX 就像个绝世美人，不时让你为她的美貌倾倒。更大的诱惑是，你心里清楚，只要你努力，就能距离她的美貌更接近一点。"
tags:
  - R
  - LaTeX
  - bookdown
  - markdown
bibliography: [zhaor.bib]
categories: []
banner: img/banners/logo-openr.png
---

7


LaTeX 做出来的文档，确实漂亮。这种漂亮不是那种一眼就能看出哪儿漂亮的漂亮，而是一种说不出来的气质。这种气质来自字体、间距、断字等等诸多细节的堆积和交互作用。只要是用过 LaTeX 的人，拿来个文档用鼻子一闻，就知道是 Word 做的还是 LaTeX 做的。就好像你遇到了你的另一半，让你神魂颠倒，可就是说不出她究竟好在哪里; 她走在人群里，你一眼就能找到她。因为你眼里没别人。

<!--more-->

然而，这种气质不是能轻易把握的。LaTeX 最为奇特的是，你为她投入了无数的时间，却竟然说不清楚到底是因为她太好还是她太糟。如果她太好，为何这么难用？如果她太糟，为何你甘心为她付出？

之所以能用 LaTeX 写完博士论文，我想来想去，这个奇迹是以下四点一起促成的：

1. 组里的同事提供了现成的论文模板，

2. 身边有同事可以随时问，

3. 老板只看结果，对我实现的手段并不介意，

4. 论文是英文写的，不需要跟中文排版死磕。

想学 LaTeX 的注意了！以上四点，只要缺了一样，那么学 LaTeX 的阻力就会提高一个数量级。此坑慎入！

如果有了这四个条件，那么基本上就不用额外操心，只管埋头写论文就是了。

然而，LaTeX 下埋头写作的体验并不美好。那感觉根本就不是写论文，而是写代码。不编译出来，你根本不知道自己写了几页，每页是啥模样。一天下来，脑袋胀胀的，心里乱乱的。相比之下，用 Word 写论文，每敲一个字符都有一点成就感，敲完一页后，就像已经出版了一样心满意足。

LaTeX 就像个绝世美人，不时让你为她的美貌倾倒。更大的诱惑是，你心里清楚，只要你努力，就能距离她的美貌更接近一点。于是，你就身不由己地投入大把大把的精力，把你的文档弄得越来越漂亮，虽然每次只是漂亮了那么一点点。

不像 Word，你知道，无论再怎么使劲，做出来的论文顶多也就那样了，不可能更美，所以心态反而平静下来，老老实实过日子。

一个像恋爱，一个像婚姻。


8

当完成博士论文的时候，我决定结束天天心惊胆战的 LaTeX 爱情长跑，回到 Word 的温柔乡。我把城墙修高加厚，厚得就像特洛伊城，把 LaTeX 拦住墙外，从此一刀两断。曾经在同一个战壕里的战友，变成了洪水猛兽。

到了新工作单位，观察了一下，老板和同事全部是正常人，不是 X-men。我松了一口气。

有一次，有个名叫 LyX 的使者来敲我的城门。从三个字母参差不齐的模样，我一眼就识破了他的伪装，知道是 LaTeX 派来的奸细，于是我轻轻吐出一个字：滚。

我以为，从此就跟 LaTeX 形同陌路了。

有一天，我在使用 R 语言的时候，神使鬼差地装上了一个名叫 bookdown 的扩展包。

很久以后，再次回忆那一刻，仍然不由得感慨万千。命中注定的事，逃不掉的劫数。

bookdown，就是攻陷特洛伊的木马; 里面藏着的，除了我的旧爱 LaTeX，还有 Pandoc 这个魔鬼。后者从名字上一看，就知道是潘多拉放出来的。

安装 bookdown 的那一瞬间，我把木马轰隆隆地拉进了我的城，而我却浑然不知。

特洛伊，就此沦陷。
